AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ingest-app

  Sample SAM Template for ingest-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  InBucket:
    Type: AWS::S3::Bucket
  OutBucket:
    Type: AWS::S3::Bucket
  IngestorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ingestor/
      Events:
        YoScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/2 * * * ? *)
            Input: '{"message": "Yo!"}'
        HeyScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(1/2 * * * ? *)
            Input: '{"message": "Hey!"}'
      Environment:
        Variables:
          IN_BUCKET: !Ref InBucket
          OUT_BUCKET: !Ref OutBucket
          IN_FILE: input.xml
          OUT_FILE: output.xml
      Handler: app.lambda_handler
      Policies:
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Join ['', [!GetAtt InBucket.Arn, '/*']]
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Join ['', [!GetAtt OutBucket.Arn, '/*']]
      Runtime: python3.9
      Architectures:
        - x86_64

Outputs:
  IngestorFunction:
    Description: "Ingestor Lambda Function ARN"
    Value: !GetAtt IngestorFunction.Arn
  IngestorFunctionIamRole:
    Description: "Implicit IAM Role created for Ingestor function"
    Value: !GetAtt IngestorFunctionRole.Arn
  InBucket:
    Description: S3 Bucket for input
    Value: !Ref InBucket
  OutBucket:
    Description: S3 Bucket for output
    Value: !Ref OutBucket

